hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "6e4a1ad878793ab3c3b7df30ea8e4177a65c3632d1b35277683d6f6b333cb073"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "e014ad2b1396a9f75c0e833808ca4a068543f705cf983b67afe1e1b631a3653f"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "ce455f3b3549ff0974cd10658aeb66f2ff39ea069c4c0d38f2ef8c692fabb3d5"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "02b86828f925b9c077affdcad610425414931c7dbe083fef42e3743acc80f7ab"
metafile = true

[[files]]
file = "mods/cave-dust.pw.toml"
hash = "8bbe5e19d1b45b336eb38e38b9cc9fba2d92baa48e35bf947abd3b73f402451c"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "0355b81b049cfd99a5329a9c8a9fad50d2a3e2069276c1cfcc3a07eb95cf3b31"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "48fa9a6af8274d7ef20978f7715789244f56364477bb5af663ff710669561ef9"
metafile = true

[[files]]
file = "mods/clean-f3.pw.toml"
hash = "73ca360d1e06a82d5bf205d3898b420674bd5e85e3626f37f9ae7a10dc48beb1"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "9a0135fbcfdc8f9efbed49fcb2e5641272ed218553cc37897eea94eb4fe47f1b"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "0f24f7bd2057b70b6816de4e66922b64f8b6635dc603e40cc45d62646dc7221d"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "45b274a21c31e0150f8984479ade9ad970d6dea8af8b65109ac711d946817568"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "da7d89a5ef4c67e74396b4a1decc94331260ec76c72723bcde45e048904cf0e2"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
hash = "616c7ca64b9f4af3f5283eaae4cb0be10cff8059e8db9c4e7d7b4422474aa8b1"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "17e8390283fd3f6a959e8c6ed234d82ffe218b21cfe2d1576889a626b45f3f63"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "f18b9c834897c055f7d729dde0d754aa80b515ea6f7c19bc0df718b0f0a48650"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "de858d34871042c79ee2a664582c1be5afee9421a870038f8cbeba520d406181"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "27ac8197dad6a1d489a153c86559915412b03e9101173694a5a22ad9a2b2ab43"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "e9870688b5c78a9cc50f79922fdac81e1999279f5567cd5092952adaf6471313"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
hash = "9baaaf98f919bf3258f50ae0b8552a53c16d298650cb90d48cbec6f96d1ef556"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "1f6c74d7140e368e85df87d1bdbb4b533052488dcee7e23ecc1f699dfd2efe82"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "078c828454d8a361baae372b5ee3dc33e5f3573fa19bdac8589b38da9dbc5c03"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "e50356ad64c98c60fefee435fedb4fa306c3295f78047c9da1e16eac227964b1"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "855342383405534bab9335c187eb9d267ce75b295c26c461f44f5e22aeaa0874"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "dfc7306d9eeaa3f4ddb22e6ef73141eba09f1891a584fdeeacaa9fbb2d182a77"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "35a5bdcb09b0b51a4161a62c0b8ab507cb58a936f036f60410704b291134d1ba"
metafile = true

[[files]]
file = "mods/item-highlighter.pw.toml"
hash = "55a94ed5f837d322444d13d39d1feaa71663511608ca4b00187793f9688f7d34"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "4ee72fa3b6d91ccec6ec3420396db368dc5097350ee2bb909af3a65f0446c9d5"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "019e6f258127d947cf0b43227c198365b107e35d4e16e29ee8388986aaf62d77"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "51d318e0a4bc5da935a965860b815a6cb57b6ef0ff046a1c364996ca784b1582"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e37792db4c4b69e11243c7470f0f2a791dc016381e460cd5616eccb6b567b5ab"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6ff1d7cc8800c891723375aea3426b9b2f50400798374e8f97f96e804cc5c518"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "da02b5c6372cb22f9a92f94811e1beed07fa2205529c9c73fc1398ed50144cd4"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "100a5dfaccb55b107edc57e11fafc1222dc443ce9b669f0d79a39b488e3e45ae"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "8221d0376bdd5c13684d44ce2dcfc994f4aeea8d21546b9a562e71517ba1ce80"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "5bef9a443c12a13d5eeefa60bbb0a40ef99ab8a0675cd335a6cc2520dc5ba33b"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "46af7d3bd6fec707eb0d9aac51c4cd1a85888266cf250b4dae7b2780487df7fb"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "6337ceb74ee951a937b2768544a1bf11812aa92628a81b9a13e66c687f9853fb"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "8f541ff641df705e688c2f1f3df042527e8c33e096ab5e62252e6b6c88daba84"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "28f2167da063c1be7b1f4e534cdcbb446daa569cc32ffe1c0705663a9a06a5b9"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "7cb74081033769dbc3d65702e4ddcf83e4a8152f7e6122ea50d7e98909c3e549"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "69ccdcf6c29d4809741828fbc9e6299f832c613c2f7db25de0bfae9f00290db6"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "e9f628cc8d3a658a9b0ceb2272993d0dd9f5736aad1fb8178e6071cd63a8438e"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "7f7768f2047011ed61c9bbec29bbcd2d06c5eb8ab731d442b9ecc2c01bbc8c6b"
metafile = true

[[files]]
file = "mods/yeetus-experimentus.pw.toml"
hash = "e3d2c86495b2695080068538e80d16049f9ea80bc131a19afd43fcaa9babee84"
metafile = true

[[files]]
file = "resourcepacks/pixlli.pw.toml"
hash = "6854227f3d1b5e21a64d14047d9488dffb125b19d6ded8c58e26d3662a24fc2d"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "f1ce0778845c0a21e9ec09f582e16d4395d6a226e3eae95dfe8421c7a9ff4d83"
metafile = true
