name = "Architects Land - Terre des Civilisations (Client)"
author = "Anhgelus Morhtuuzh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62e165f45fc55c068e1a6c2657d6f8c608833e060edfbb4a1779c31fdcc91a45"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
